version: '3'
services:
  demosite:
    image: nginx:latest
    restart: always
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    container_name: "demosite"